spring:
    data:
        mongodb:
            uri : mongodb+srv://isuru:1234@db01.lterdlp.mongodb.net/test
            database: Foodies
    
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-8p8r54c7lh326yqn.us.auth0.com/
auth0:
    audience: http://localhost:8095
